### ISSUE TITLE
Upgrade fish shell version from 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by frederickjh** [xxh/fish-portable#1]
Upgrade fish shell to the newest version. 3.2.0 has been out one week now.

**Comment by anki-code** [comment]
Yep! PR is welcome!

**Comment by frederickjh** [comment]
Just got an email from the fish shell issue regarding Appimages with a [new comment](https://github.com/fish-shell/fish-shell/issues/6475#issuecomment-797410734), saying that there are now nightly appimage builds and asking if there is a 3.2.0 one that they can upload to the [fishshell.com](https://fishshell.com) site.

**Comment by anki-code** [comment]
Thank you for keeping in touch! I don't understand the question that asked in the thread.

**Comment by frederickjh** [comment]
faho is asking if there are appimages for fish shell version 3.2.0 that are already being built that can be included on the fish shell download page. 
So, maybe that appimage could be used instead of using this project to make a newer version of xxh-shell-fish-appimage that is used with xxh-shell-fish.

**Comment by anki-code** [comment]
Sorry, still don't understand. May be it's friday mode ) 
But they already had nightly builds a year ago but with wrong docker image (not manylinux). What we should do?

**Comment by anki-code** [comment]
@frederickjh Ah, you mean we should rebuild the current version in this repo. Done! Please try it in action.

**Comment by frederickjh** [comment]
Fish 3.2.0 seems to be working fine. Closing.
